# Hotel review → amenity mention starter

This notebook is a debugging-first starter for a **2-stage pipeline**:

1. **Retrieve** likely hotel amenities for each review chunk using embeddings  
2. **Verify** each candidate with a cheap structured-output model call

It is wired to your uploaded schema:

- `Description_PROC.csv` for hotel amenity inventory
- `Reviews_PROC.csv` for review text keyed by `eg_property_id`

In [33]:
from pathlib import Path
import os
import pandas as pd
from dotenv import load_dotenv

DESCRIPTION_CSV = "../sources/Description_PROC.csv"
REVIEWS_CSV = "../sources/Reviews_PROC.csv"

DESCRIPTION_CSV, REVIEWS_CSV

('../sources/Description_PROC.csv', '../sources/Reviews_PROC.csv')

In [34]:
from hotel_review_amenity_pipeline_v2 import (
    load_input_data,
    build_amenity_catalog,
    build_review_chunk_table,
    get_client,
    embed_texts,
    build_hotel_amenity_index,
    retrieve_top_amenity_candidates,
    verify_candidates_dataframe,
    process_reviews,
    build_unique_amenity_vocab,
    bootstrap_amenity_mapping,
    canonicalize_amenity_vocab_with_model,
    save_amenity_mapping,
    load_amenity_mapping,
)

client = get_client(os.getenv("api_key"))

description_df, reviews_df = load_input_data(DESCRIPTION_CSV, REVIEWS_CSV)

print(description_df.shape)
print(reviews_df.shape)
display(description_df.head(2))
display(reviews_df.head(5))

(13, 31)
(5999, 6)

,eg_property_id,guestrating_avg_expedia,city,province,country,star_rating,area_description,property_description,popular_amenities_list,property_amenity_accessibility,...,property_amenity_spa,property_amenity_things_to_do,check_in_start_time,check_in_end_time,check_out_time,check_out_policy,pet_policy,children_and_extra_bed_policy,check_in_instructions,know_before_you_go
0,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,8.4,Pompei,NaN,Italy,NaN,"located in |MASK|, hotel |MASK| |MASK| is in t...","hotel with a restaurant, steps from pompeii ar...","[""ac"", ""bar"", ""breakfast_included"", ""frontdesk...","[""this property does not have elevators""]",...,NaN,"[""shopping""]",2:00 PM,midnight,11:00 AM,"[""Check-out before 11 AM""]","[""Pets not allowed""]","[""<ul><li>Children are welcome.</li></ul><ul><...","[""front desk staff will greet guests on arriva...","[""all guests, including children, must be pres..."
1,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,9.2,Broomfield,Colorado,United States,4.0,"located in broomfield, |MASK| |MASK| is in the...","suburban resort with 3 restaurants, in the vic...","[""ac"", ""bar"", ""breakfast_available"", ""business...","[""assistive listening devices available"", ""ele...",...,"[""6 treatment rooms"", ""aromatherapy"", ""body sc...","[""2 outdoor pools"", ""24-hour fitness center"", ...",4:00 PM,anytime,11:00 AM,"[""A late check-out fee will be charged"", ""Chec...","[""1 total (up to 70 lbs per pet)"", ""Food and w...","[""<ul><li>Children are welcome.</li></ul><ul><...","[""front desk staff will greet guests on arriva...","[""a car is not required for transportation to ..."

,eg_property_id,acquisition_date,lob,rating,review_title,review_text
0,9a0043fd4258a1286db1e253ca591662b3aac849da12d0...,2/10/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 4.0, ""serv...",NaN,mir hat der service gut gefallen.
1,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,2/14/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",NaN,great
2,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,2/14/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 4.0, ""serv...",NaN,convenient to shopping and dining options. go...
3,3216b1b7885bffdb336265a8de7322ba0cd477cfb3d4f9...,2/8/23,HOTEL,"{""overall"": 3.0, ""roomcleanliness"": 3.0, ""serv...",NaN,good regular clean place
4,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,2/9/23,HOTEL,"{""overall"": 4.0, ""roomcleanliness"": 4.0, ""serv...",NaN,location was good

In [35]:
vocab_df = build_unique_amenity_vocab(description_df)
mapping_df = bootstrap_amenity_mapping(vocab_df)

# optional one-time model cleanup pass
mapping_df = canonicalize_amenity_vocab_with_model(
    client,
    vocab_df,
    model="gpt-5.4-mini",
    batch_size=150,
    use_rule_bootstrap=True,
)

display(mapping_df.head(30))

,raw_amenity_value,action,canonical_name,canonical_category,canonical_description,reason,normalized_raw_amenity_value
0,elevator,keep,elevator,accessibility,Elevator or lift access within the property.,core accessibility amenity,elevator
1,available in all rooms: free wifi,merge,free wifi,wifi,Free wireless internet available in guest rooms.,normalize internet wording to wifi concept,available in all rooms free wifi
2,internet,merge,wifi,wifi,Internet access or wireless internet availabil...,broad internet concept; useful for review matc...,internet
3,available in some public areas: free wifi,merge,free wifi,wifi,Free wireless internet available in some publi...,normalize internet wording to wifi concept,available in some public areas free wifi
4,english,drop,,,,language label does not describe an amenity co...,english
5,ac,merge,air conditioning,comfort,Guestroom or property air conditioning.,common abbreviation for air conditioning,ac
6,daily housekeeping,merge,housekeeping,service,"Housekeeping or room cleaning service, includi...",specific frequency should map to general house...,daily housekeeping
7,housekeeping,keep,housekeeping,service,Housekeeping or room cleaning service.,useful broad service amenity,housekeeping
8,if you have requests for specific accessibilit...,drop,,,,"policy/instruction text, not an amenity",if you have requests for specific accessibilit...
9,24-hour front desk,merge,24 hour front desk,service,Front desk staffed around the clock.,standardized time formatting,24 hour front desk
10,free_parking,merge,free parking,parking,Complimentary parking at or near the property.,normalize to parking concept,free parking
11,frontdesk_24_hour,merge,24 hour front desk,service,Front desk staffed around the clock.,duplicate wording for 24-hour front desk,frontdesk 24 hour
12,laundry,merge,laundry service,service,Laundry service or self-service laundry facili...,standalone laundry is ambiguous; broaden to la...,laundry
13,laundry facilities,merge,laundry service,service,Laundry service or self-service laundry facili...,broad laundry concept,laundry facilities
14,luggage storage,keep,luggage storage,service,Secure storage for guest luggage.,clear guest service amenity,luggage storage
15,front-desk safe,keep,front desk safe,service,Safe available at the front desk for guest val...,clear service amenity,front desk safe
16,no_smoking,merge,non smoking property,policy,Property or rooms designated as non-smoking.,normalize smoke policy to standard concept,no smoking
17,outdoor_space,merge,outdoor space,outdoor,"General outdoor guest space such as patio, gar...",broad outdoor amenity,outdoor space
18,smoke-free property,merge,non smoking property,policy,Property or rooms designated as non-smoking.,duplicate smoke policy concept,smoke free property
19,business_services,merge,business services,business,Business-related guest services and facilities.,normalize underscored label to canonical busin...,business services
20,microwave,keep,microwave,in-room,Microwave available in room or shared guest area.,useful concrete room amenity,microwave
21,restaurant,keep,restaurant,dining,On-property restaurant or dining venue.,already a good canonical dining concept,restaurant
22,tv,keep,tv,in-room,Television available in room or common area.,common in-room amenity,tv
23,banquet hall,keep,banquet hall,event,Banquet or event hall space.,distinct event facility,banquet hall
24,dry cleaning service,merge,dry cleaning,service,Dry cleaning service for guest clothing.,service normalization,dry cleaning service
25,free self parking on site,merge,free parking,parking,Complimentary parking at or near the property.,specific parking variant,free self parking on site
26,1 restaurant,merge,restaurant,dining,On-property restaurant or dining venue.,count should not create separate concept,1 restaurant
27,bar,keep,bar,dining,On-property bar or lounge serving drinks.,useful dining/drinks amenity,bar
28,breakfast_available,merge,breakfast,dining,Breakfast service availability.,normalize to breakfast concept,breakfast available
29,garden,keep,garden,outdoor,Garden or landscaped outdoor area.,clear outdoor amenity,garden

In [36]:
amenity_catalog_df = build_amenity_catalog(description_df)

print("Hotels:", amenity_catalog_df["eg_property_id"].nunique())
print("Amenity rows:", len(amenity_catalog_df))
display(amenity_catalog_df.head(20))

Hotels: 13
Amenity rows: 694

,amenity_id,eg_property_id,source_column,source_category,amenity_category,raw_amenity_value,amenity_name,mapping_action,amenity_embedding_text
0,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,popular_amenities_list,popular amenities,popular amenities,ac,ac,keep,Hotel amenity mention candidate. Canonical cat...
1,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,popular_amenities_list,popular amenities,popular amenities,bar,bar,keep,Hotel amenity mention candidate. Canonical cat...
2,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,popular_amenities_list,popular amenities,popular amenities,breakfast_included,breakfast included,keep,Hotel amenity mention candidate. Canonical cat...
3,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,popular_amenities_list,popular amenities,popular amenities,frontdesk_24_hour,frontdesk 24 hour,keep,Hotel amenity mention candidate. Canonical cat...
4,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,popular_amenities_list,popular amenities,popular amenities,housekeeping,housekeeping,keep,Hotel amenity mention candidate. Canonical cat...
5,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,popular_amenities_list,popular amenities,popular amenities,internet,internet,keep,Hotel amenity mention candidate. Canonical cat...
6,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,popular_amenities_list,popular amenities,popular amenities,no_smoking,no smoking,keep,Hotel amenity mention candidate. Canonical cat...
7,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,popular_amenities_list,popular amenities,popular amenities,outdoor_space,outdoor space,keep,Hotel amenity mention candidate. Canonical cat...
8,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,popular_amenities_list,popular amenities,popular amenities,restaurant,restaurant,keep,Hotel amenity mention candidate. Canonical cat...
9,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,popular_amenities_list,popular amenities,popular amenities,tv,tv,keep,Hotel amenity mention candidate. Canonical cat...
10,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,property_amenity_accessibility,accessibility,accessibility,this property does not have elevators,this property does not have elevators,keep,Hotel amenity mention candidate. Canonical cat...
11,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,property_amenity_conveniences,conveniences,conveniences,front-desk safe,front desk safe,keep,Hotel amenity mention candidate. Canonical cat...
12,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,property_amenity_conveniences,conveniences,conveniences,vending machine,vending machine,keep,Hotel amenity mention candidate. Canonical cat...
13,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,property_amenity_family_friendly,family friendly,family friendly,snack bar/deli,snack bar/deli,keep,Hotel amenity mention candidate. Canonical cat...
14,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,property_amenity_food_and_drink,food and drink,food and drink,1 bar,1 bar,keep,Hotel amenity mention candidate. Canonical cat...
15,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,property_amenity_food_and_drink,food and drink,food and drink,1 restaurant,1 restaurant,keep,Hotel amenity mention candidate. Canonical cat...
16,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,property_amenity_food_and_drink,food and drink,food and drink,free buffet breakfast,free buffet breakfast,keep,Hotel amenity mention candidate. Canonical cat...
17,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,property_amenity_guest_services,guest services,guest services,24-hour front desk,24 hour front desk,keep,Hotel amenity mention candidate. Canonical cat...
18,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,property_amenity_guest_services,guest services,guest services,daily housekeeping,daily housekeeping,keep,Hotel amenity mention candidate. Canonical cat...
19,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,110f01b8ae518a0ee41047bce5c22572988a435e10ead7...,property_amenity_guest_services,guest services,guest services,luggage storage,luggage storage,keep,Hotel amenity mention candidate. Canonical cat...

In [37]:
chunk_df = build_review_chunk_table(reviews_df.head(10), max_chars=320)

print("Chunk rows:", len(chunk_df))
display(chunk_df.head(20))

Chunk rows: 10

,review_id,eg_property_id,acquisition_date,lob,rating,chunk_id,chunk_text
0,0,9a0043fd4258a1286db1e253ca591662b3aac849da12d0...,2/10/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 4.0, ""serv...",0,mir hat der service gut gefallen.
1,1,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,2/14/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",0,great
2,2,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,2/14/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 4.0, ""serv...",0,convenient to shopping and dining options. goo...
3,3,3216b1b7885bffdb336265a8de7322ba0cd477cfb3d4f9...,2/8/23,HOTEL,"{""overall"": 3.0, ""roomcleanliness"": 3.0, ""serv...",0,good regular clean place
4,4,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,2/9/23,HOTEL,"{""overall"": 4.0, ""roomcleanliness"": 4.0, ""serv...",0,location was good
5,5,fa014137b3ea9af6a90c0a86a1d099e46f7e56d6eb33db...,2/13/23,HOTEL,"{""overall"": 4.0, ""roomcleanliness"": 5.0, ""serv...",0,"we weren’t allowed to check in early, but that..."
6,7,fa014137b3ea9af6a90c0a86a1d099e46f7e56d6eb33db...,2/13/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 0.0, ""serv...",0,very clean and great location
7,8,3216b1b7885bffdb336265a8de7322ba0cd477cfb3d4f9...,2/13/23,HOTEL,"{""overall"": 2.0, ""roomcleanliness"": 1.0, ""serv...",0,this property is filthy!! the walls of the roo...
8,8,3216b1b7885bffdb336265a8de7322ba0cd477cfb3d4f9...,2/13/23,HOTEL,"{""overall"": 2.0, ""roomcleanliness"": 1.0, ""serv...",1,"location is not good, but it was necessary for..."
9,9,3216b1b7885bffdb336265a8de7322ba0cd477cfb3d4f9...,2/26/23,HOTEL,"{""overall"": 3.0, ""roomcleanliness"": 3.0, ""serv...",0,it couldve been worse. we had to change rooms ...

## Retrieval-only smoke test

This lets you check whether the top candidates make sense **before** paying for verifier calls.

In [38]:
# Build hotel amenity index once.
amenity_embeddings = embed_texts(
    client,
    amenity_catalog_df["amenity_embedding_text"].tolist(),
    model="text-embedding-3-small",
)
hotel_index = build_hotel_amenity_index(amenity_catalog_df, amenity_embeddings)

# Pick one review to inspect manually.
sample_review = reviews_df.iloc[[1]].copy()
sample_chunks = build_review_chunk_table(sample_review, max_chars=320)
sample_chunk_embeddings = embed_texts(
    client,
    sample_chunks["chunk_text"].tolist(),
    model="text-embedding-3-small",
)

retrieved = retrieve_top_amenity_candidates(
    hotel_index=hotel_index,
    property_id=str(sample_review["eg_property_id"].iloc[0]),
    chunk_texts=sample_chunks["chunk_text"].tolist(),
    chunk_embeddings=sample_chunk_embeddings,
    top_k=5,
    min_similarity=0.4,
)

display(sample_review)
display(sample_chunks)
if retrieved.empty:
    display(retrieved)
else:
    display(retrieved.sort_values("retrieval_score", ascending=False))

,eg_property_id,acquisition_date,lob,rating,review_title,review_text
1,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,2/14/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",NaN,great

,review_id,eg_property_id,acquisition_date,lob,rating,chunk_id,chunk_text
0,0,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,2/14/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",0,great

Empty DataFrame
Columns: [chunk_id, chunk_text, amenity_id, amenity_name, amenity_category, raw_amenity_value, retrieval_score]
Index: []

## Add the verifier

Default is `gpt-5.4-nano` to keep costs down.  
If you want more quality, switch to `gpt-5.4-mini`.

In [39]:
top_candidates = (
    retrieved
    if retrieved.empty or "retrieval_score" not in retrieved.columns
    else retrieved.sort_values("retrieval_score", ascending=False).head(8)
)

verified = verify_candidates_dataframe(
    client,
    top_candidates,
    model="gpt-5.4-nano",
)

display(verified)

Empty DataFrame
Columns: []
Index: []

## Run a small batch end-to-end

Start small. Tune your thresholds and prompts on a subset before scaling up.

In [47]:
sample_reviews = reviews_df.head(500).copy()

amenity_catalog_df, mentions_df, summary_df = process_reviews(
    client=client,
    description_df=description_df,
    reviews_df=sample_reviews,
    amenity_mapping_df=mapping_df,
    embedding_model="text-embedding-3-small",
    verifier_model="gpt-5.4-nano",
    top_k=3,
    min_similarity=0.4,
    verify=True,
    max_verifications_per_review=8,
)

display(mentions_df.head(30))
display(summary_df.head(30))

,chunk_id,chunk_text,amenity_id,amenity_name,amenity_category,raw_amenity_value,retrieval_score,review_id,eg_property_id,acquisition_date,lob,rating,mentioned,explicitness,sentiment,evidence,rationale_short
0,0,convenient to shopping and dining options. goo...,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,conference space,business services,conference space (1122 square feet),0.405563,2,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,2/14/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 4.0, ""serv...",False,not_mentioned,unknown,good business hotel.,The chunk mentions being a business hotel and ...
1,0,easy access from 75 clean breakfast included r...,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,free continental breakfast,dining,free continental breakfast available 6:00 am–9...,0.428353,10,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,3/1/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 0.0, ""serv...",True,implicit,positive,clean breakfast included,The chunk explicitly indicates breakfast is in...
2,0,easy access from 75 clean breakfast included r...,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,breakfast,dining,breakfast_included,0.408313,10,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,3/1/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 0.0, ""serv...",True,explicit,positive,clean breakfast included,The chunk explicitly says breakfast was included.
3,0,"reall clean, nice, and safe hotel. ample parki...",ff26cdda236b233f7c481f0e896814075ac6bed335e162...,free parking,parking,free self parking on site,0.417003,20,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,2/23/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",False,not_mentioned,positive,ample parking,"The chunk mentions parking availability, but i..."
4,0,"reall clean, nice, and safe hotel. ample parki...",ff26cdda236b233f7c481f0e896814075ac6bed335e162...,free parking,parking,free_parking,0.408771,20,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,2/23/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",False,not_mentioned,positive,ample parking,"The chunk mentions parking availability, but i..."
5,0,the entire hotel property provides lots of lar...,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,conference space,business services,conference space (40000 square feet),0.446768,56,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,2/28/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 4.0, ""serv...",True,implicit,positive,provides lots of large spaces for hanging out ...,The chunk mentions large on-property spaces su...
6,0,the entire hotel property provides lots of lar...,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,ballroom,event,ballroom,0.443991,56,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,2/28/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 4.0, ""serv...",True,implicit,positive,the entire hotel property provides lots of lar...,The chunk mentions large on-site spaces for en...
7,0,super convenient and stylish hotel. absolutely...,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,24 hour front desk,service,frontdesk_24_hour,0.402635,59,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,2/28/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",False,not_mentioned,positive,absolutely loved the staff. so welcoming and v...,The chunk praises staff hospitality but does n...
8,1,"breakfast was not included, but enjoyed a beau...",ff26cdda236b233f7c481f0e896814075ac6bed335e162...,cooked-to-order breakfast available for a fee,dining,cooked-to-order breakfast available for a fee ...,0.436183,69,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,2/28/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",True,implicit,positive,enjoyed a beautifully presented breakfast at t...,The guest refers to having breakfast at the ho...
9,1,"breakfast was not included, but enjoyed a beau...",ff26cdda236b233f7c481f0e896814075ac6bed335e162...,breakfast,dining,breakfast_available,0.420187,69,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,2/28/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",True,explicit,mixed,"breakfast was not included, but enjoyed a beau...",The reviewer discusses breakfast being availab...
10,0,the service and restaurants were top notch. th...,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,free area shuttle,transportation,free area shuttle up to 3 miles,0.451478,74,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,2/28/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 4.0, ""serv...",True,explicit,positive,the shuttle was very convenient,The chunk explicitly mentions a hotel shuttle ...
11,0,the service and restaurants were top notch. th...,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,free area shuttle,transport,free area shuttle,0.437545,74,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,2/28/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 4.0, ""serv...",True,explicit,positive,the shuttle was very convenient,The chunk explicitly mentions a convenient shu...
12,0,the service and restaurants were top notch. th...,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,shopping center shuttle,transportation,free shopping center shuttle,0.417714,74,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,2/28/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 4.0, ""serv...",False,not_mentioned,neutral,the shuttle was very convenient,"The chunk mentions a shuttle, but it does not ..."
13,2,the parking is in a garage underneath the hote...,fa014137b3ea9af6a90c0a86a1d099e46f7e56d6eb33db...,covered self parking,parking,free covered self parking on site,0.415399,79,fa014137b3ea9af6a90c0a86a1d099e46f7e56d6eb33db...,2/28/23,HOTEL,"{""overall"": 4.0, ""roomcleanliness"": 4.0, ""serv...",True,explicit,neutral,the parking is in a garage underneath the hotel.,The chunk explicitly describes the hotel’s par...
14,2,the parking is in a garage underneath the hote...,fa014137b3ea9af6a90c0a86a1d099e46f7e56d6eb33db...,free parking,parking,free_parking,0.407064,79,fa014137b3ea9af6a90c0a86a1d099e46f7e56d6eb33db...,2/28/23,HOTEL,"{""overall"": 4.0, ""roomcleanliness"": 4.0, ""serv...",False,not_mentioned,unknown,the parking is in a garage underneath the hotel.,"The chunk mentions parking, but it does not st..."
15,0,we appreciated the friendly and helpfulness of...,fa014137b3ea9af6a90c0a86a1d099e46f7e56d6eb33db...,multilingual staff,service,multilingual staff,0.405568,102,fa014137b3ea9af6a90c0a86a1d099e46f7e56d6eb33db...,3/2/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",False,not_mentioned,positive,friendly and helpfulness of all property staff,The chunk praises staff friendliness/helpfulne...
16,0,the property offers a relaxing atmosphere. the...,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,hot tub,pool,hot tub,0.424819,129,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,7/18/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",True,explicit,positive,there is an outdoor hot tub which was pleasant...,The chunk explicitly mentions an outdoor hot t...
17,0,the property offers a relaxing atmosphere. the...,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,hot tub,pool,hot_tub,0.421692,129,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,7/18/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",True,explicit,positive,there is an outdoor hot tub which was pleasant...,The chunk explicitly mentions an outdoor hot t...
18,4,we only ate breakfast there but at three euros...,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,breakfast,dining,buffet breakfast available for a fee daily 6:3...,0.460929,132,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,3/2/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",True,explicit,positive,we only ate breakfast there but at three euros...,The chunk directly discusses the hotel’s break...
19,3,"the room is modern, clean with air conditionin...",823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,air conditioning,comfort,ac,0.413557,132,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,3/2/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",True,explicit,positive,with air conditioning,The chunk explicitly mentions the room having ...
20,0,early check in friendly staff perfect room goo...,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,free continental breakfast,dining,free continental breakfast available 6:00 am–9...,0.440264,144,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,3/2/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",True,explicit,positive,perfect room good breakfast,The review explicitly mentions “good breakfast...
21,0,early check in friendly staff perfect room goo...,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,24 hour front desk,service,frontdesk_24_hour,0.421595,144,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,3/2/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",False,not_mentioned,positive,friendly staff,The chunk mentions friendly staff and early ch...
22,0,early check in friendly staff perfect room goo...,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,breakfast,dining,breakfast_included,0.418393,144,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,3/2/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",True,explicit,positive,good breakfast,The chunk explicitly mentions that the breakfa...
23,0,close to the beach,f2d8d9557208d58577e9df7ff34e42bf86fb5b10fdfae0...,beachfront,outdoor,beachfront location,0.416711,145,f2d8d9557208d58577e9df7ff34e42bf86fb5b10fdfae0...,3/2/23,HOTEL,"{""overall"": 3.0, ""roomcleanliness"": 4.0, ""serv...",True,implicit,neutral,close to the beach,Saying the hotel is close to the beach indicat...
24,1,"i loved the lobby area with fireplace, cozy an...",db38b19b897dbece3e34919c662b3fd66d23b615395d11...,fireplace in lobby,common area,fireplace in lobby,0.480070,165,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,3/6/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",True,explicit,positive,"loved the lobby area with fireplace, cozy and ...",The review explicitly praises a fireplace in t...
25,1,"i loved the lobby area with fireplace, cozy an...",db38b19b897dbece3e34919c662b3fd66d23b615395d11...,bar,dining,1 poolside bar and 1 bar,0.421971,165,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,3/6/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",True,implicit,positive,a nice dinner and drink at a very fun restaura...,The review explicitly refers to having drinks ...
26,1,"i loved the lobby area with fireplace, cozy an...",db38b19b897dbece3e34919c662b3fd66d23b615395d11...,bar,dining,bar,0.410700,165,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,3/6/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",True,explicit,positive,a nice dinner and drink at a very fun restaura...,The review explicitly mentions having dinner a...
27,0,"amazing staff at check in and check out, in th...",db38b19b897dbece3e34919c662b3fd66d23b615395d11...,multilingual staff,service,multilingual staff,0.407746,165,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,3/6/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",False,not_mentioned,positive,amazing staff at check in and check out,The chunk praises staff and their thoughtfulne...
28,0,"amazing staff at check in and check out, in th...",db38b19b897dbece3e34919c662b3fd66d23b615395d11...,24 hour front desk,service,24-hour front desk,0.407571,165,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,3/6/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",False,not_mentioned,positive,amazing staff at check in and check out,The chunk praises staff during check-in/check-...
29,0,"amazing staff at check in and check out, in th...",db38b19b897dbece3e34919c662b3fd66d23b615395d11...,24 hour front desk,service,frontdesk_24_hour,0.405568,165,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,3/6/23,HOTEL,"{""overall"": 5.0, ""roomcleanliness"": 5.0, ""serv...",False,not_mentioned,positive,amazing staff at check in and check out,The chunk praises staff at check-in/check-out ...

,review_id,amenity_id,amenity_name,amenity_category,eg_property_id,best_retrieval_score,mention_count,sample_evidence,sentiment
0,10,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,free continental breakfast,dining,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,0.428353,1,clean breakfast included,positive
1,10,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,breakfast,dining,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,0.408313,1,clean breakfast included,positive
2,56,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,conference space,business services,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.446768,1,provides lots of large spaces for hanging out ...,positive
3,56,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,ballroom,event,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.443991,1,the entire hotel property provides lots of lar...,positive
4,69,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,cooked-to-order breakfast available for a fee,dining,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,0.436183,1,enjoyed a beautifully presented breakfast at t...,positive
5,69,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,breakfast,dining,ff26cdda236b233f7c481f0e896814075ac6bed335e162...,0.420187,1,"breakfast was not included, but enjoyed a beau...",mixed
6,74,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,free area shuttle,transportation,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.451478,1,the shuttle was very convenient,positive
7,74,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,free area shuttle,transport,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.437545,1,the shuttle was very convenient,positive
8,79,fa014137b3ea9af6a90c0a86a1d099e46f7e56d6eb33db...,covered self parking,parking,fa014137b3ea9af6a90c0a86a1d099e46f7e56d6eb33db...,0.415399,1,the parking is in a garage underneath the hotel.,neutral
9,129,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,hot tub,pool,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.424819,1,there is an outdoor hot tub which was pleasant...,positive
10,129,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,hot tub,pool,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.421692,1,there is an outdoor hot tub which was pleasant...,positive
11,132,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,breakfast,dining,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,0.460929,1,we only ate breakfast there but at three euros...,positive
12,132,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,air conditioning,comfort,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,0.413557,1,with air conditioning,positive
13,144,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,free continental breakfast,dining,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,0.440264,1,perfect room good breakfast,positive
14,144,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,breakfast,dining,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,0.418393,1,good breakfast,positive
15,145,f2d8d9557208d58577e9df7ff34e42bf86fb5b10fdfae0...,beachfront,outdoor,f2d8d9557208d58577e9df7ff34e42bf86fb5b10fdfae0...,0.416711,1,close to the beach,neutral
16,165,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,fireplace in lobby,common area,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.480070,1,"loved the lobby area with fireplace, cozy and ...",positive
17,165,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,bar,dining,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.421971,1,a nice dinner and drink at a very fun restaura...,positive
18,165,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,bar,dining,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.410700,1,a nice dinner and drink at a very fun restaura...,positive
19,173,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,breakfast,dining,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,0.439446,1,breakfast was not good at all. bread and crois...,negative
20,173,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,free wifi,wifi,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,0.421462,1,free wifi and computer in lobby with free usag...,positive
21,173,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,free wifi,wifi,823fb2499b4e37d99acb65e7198e75965d6496fd1c579f...,0.410325,1,free wifi and computer in lobby with free usag...,positive
22,175,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,free continental breakfast,dining,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,0.419937,1,“the lady who cooks the free breakfast”,positive
23,189,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,pool,pool,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.420569,1,nice pools and hot tub.,positive
24,189,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,pool,pool,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.415039,1,nice pools and hot tub,positive
25,191,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,pool,pool,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.413644,1,the many pools were nice for people to spread out,positive
26,191,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,pool,pool,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.404092,1,the many pools were nice for people to spread out,positive
27,200,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,free continental breakfast,dining,7d027ef72c02eaa17af3c993fd5dba50d17b41a6280389...,0.427599,1,breakfast was good.,positive
28,201,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,restaurant,dining,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.450630,1,restaurant needs to be open later.,mixed
29,220,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,pool,pool,db38b19b897dbece3e34919c662b3fd66d23b615395d11...,0.498775,1,the pools are fantastic,positive

In [48]:
OUTPUT_DIR = "outputs"

amenity_catalog_df.to_csv("outputs/amenity_catalog.csv", index=False)
mentions_df.to_csv("outputs/review_chunk_mentions.csv", index=False)
summary_df.to_csv("outputs/review_amenity_summary.csv", index=False)

print("Wrote files to", OUTPUT_DIR)

Wrote files to outputs

## Suggested next steps

- Tune `min_similarity` by language and by amenity family
- Add a human-labeled eval set for precision / recall
- Cache amenity embeddings per hotel so you only re-embed when descriptions change
- Batch verifier calls offline for backfills; keep online spend bounded with `max_verifications_per_review`
- Consider a 3-band policy:
  - very high similarity → maybe skip verifier for exact matches
  - medium similarity → send to verifier
  - low similarity → reject